import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#bebfff",
        "surface-container-high": "#e6e8ea",
        "on-tertiary-fixed": "#07006c",
        "surface-variant": "#e0e3e5",
        "on-primary-container": "#c1beff",
        "tertiary-container": "#3b3bc9",
        "surface-tint": "#5148d7",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#005049",
        "on-secondary-fixed": "#00201d",
        secondary: "#006a61",
        primary: "#2a14b4",
        "on-secondary-container": "#006f66",
        "on-surface": "#191c1e",
        "surface-dim": "#d8dadc",
        "outline-variant": "#c7c4d7",
        "secondary-fixed": "#89f5e7",
        "primary-fixed-dim": "#c3c0ff",
        tertiary: "#1f1ab3",
        background: "#f7f9fb",
        "primary-container": "#4338ca",
        "tertiary-fixed-dim": "#c0c1ff",
        "secondary-container": "#86f2e4",
        "on-surface-variant": "#464554",
        "primary-fixed": "#e3dfff",
        "surface-container-highest": "#e0e3e5",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#6bd8cb",
        "on-tertiary": "#ffffff",
        "surface-container": "#eceef0",
        "surface-bright": "#f7f9fb",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#100069",
        "inverse-on-surface": "#eff1f3",
        error: "#ba1a1a",
        "tertiary-fixed": "#e1e0ff",
        "on-primary": "#ffffff",
        outline: "#777586",
        surface: "#f7f9fb",
        "surface-container-low": "#f2f4f6",
        "on-secondary": "#ffffff",
        "inverse-surface": "#2d3133",
        "on-error": "#ffffff",
        "on-background": "#191c1e",
        "on-primary-fixed-variant": "#372abf",
        "on-tertiary-fixed-variant": "#2f2ebe",
        "inverse-primary": "#c3c0ff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        base: "8px",
        xs: "4px",
        sm: "12px",
        md: "24px",
        lg: "48px",
        xl: "80px",
        gutter: "24px",
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        "sidebar-width": "280px",
      },
      fontFamily: {
        headline: ["Hanken Grotesk", "sans-serif"],
        body: ["Hanken Grotesk", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-bold": ["12px", { lineHeight: "16px", fontWeight: "600" }],
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};

export default config;
